import "styles/global.scss";
import { GeneralLayout } from 'layouts/GeneralLayout';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GeneralLayout>
          {children}
        </GeneralLayout>
      </body>
    </html>
  )
}
